from pygame import image

piecePurple = image.load("public\\images\\pieces\\purple.png")
pieceBlue = image.load("public\\images\\pieces\\blue.png")
pieceGreen = image.load("public\\images\\pieces\\green.png")
pieceGreenBlue = image.load("public\\images\\pieces\\greenBlue.png")
pieceOrange = image.load("public\\images\\pieces\\orange.png")
pieceOrangeRed = image.load("public\\images\\pieces\\orangeRed.png")
piecePink = image.load("public\\images\\pieces\\pink.png")
pieceRed = image.load("public\\images\\pieces\\red.png")
pieceYellow = image.load("public\\images\\pieces\\yellow.png")

completePiecePurple = image.load("public\\images\\completePieces\\purple.png")
completePieceBlue = image.load("public\\images\\completePieces\\blue.png")
completePieceGreen = image.load("public\\images\\completePieces\\green.png")
completePieceGreenBlue = image.load("public\\images\\completePieces\\greenBlue.png")
completePieceOrange = image.load("public\\images\\completePieces\\orange.png")
completePieceOrangeRed = image.load("public\\images\\completePieces\\orangeRed.png")
completePiecePink = image.load("public\\images\\completePieces\\pink.png")
completePieceRed = image.load("public\\images\\completePieces\\red.png")
completePieceYellow = image.load("public\\images\\completePieces\\yellow.png")